# Configuration
reinforce:
  DIAMOND: 100

  GOLD_INGOT: 50
  IRON_INGOT: 30
  COBBLESTONE: 10
  # add ID: HEALTH

messages:
  block_health: "&aBlock Health : &r%health%"
  removed: "&cYou have been removed from reinforce mode."
  added: "&aYou have been added to reinforce mode."
  prefix: "&7[&e&lReinforce&7]"
  in_modes: "&aYou are in Reinforcement mode."
  in_hand: "&cItem In Hand can add %health_to_add% Health points."
  max_health_reached: "&cSorry you cannot performed that maximum health reached (max: %max_health%)"
  block_reinforce: "&aThe block has been reinforced with %health_to_add% health points."

config:
  explosion:
    damage: 1
  max_health: 1000

